# this config is used to build the site for pr previewing
title: ABLATE Preview Docs
description: >- # this means to ignore newlines until "baseurl:"
  ABLATE aims to advance space exploration through research that will improve hybrid rocket motors and enable the next generation of low-cost space flight.
url: "http://localhost:8000" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/images/logo.png"
repository: "ubchrest/ablate"

# Aux links for the upper right navigation
aux_links:
  "CHREST on GitHub":
    - "https://github.com/UBCHREST/ablate"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme

