name: Testing

on:
  pull_request:
    branches: [ main ]

jobs:

  run-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Log into registry
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Build the Docker test image
      run: docker build . --file DockerTestFile --tag framework-test-image
        
    - name: Run the test image
      run: docker run --rm framework-test-image || echo "::error file=app.js,line=10,col=15::Unit and Integration tests have failed!"
